version: 0.0
os: linux
files:
  - source: /
    destination: /webapp-install
hooks:
  BeforeInstall:
    - location: scripts/npm-stop.sh
      runas: root
      timeout: 60
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: ubuntu
      timeout: 60